### ISSUE TITLE
Design an Item Tagging Framework

### ISSUE THREAD

**Issue by daakru** [JanikCodes/tarnished_souls#10]
There should be a common framework developed for "tagging" items to support multiple features in future development, such as
* Marking items as Favorites
* Creating entire weapon/armor loadouts that could be swapped by a single command
* Filtering by custom defined tags (essentially custom user defined Favorites groups)
* Marking items as "Do Not Sell" or "Keep 1" to prevent selling them accidentally if batch selling becomes a thing

**Comment by JanikCodes** [comment]
Filtering is also coming with the upcoming patch, it includes sub inventory categories for armor.
However I'll try to add the 'favorite' section so you can mark items as favorite and quickly find them.
