### ISSUE TITLE
Integrate Sell Option in Inventory View

### ISSUE THREAD

**Issue by daakru** [JanikCodes/tarnished_souls#11]
![label_feature-idea](https://img.shields.io/badge/label-feature%20idea-blueviolet)
I think it might be achievable to add a button to the weapon and armor views that replaces the return button with a cancel button, and the previous/next buttons with a button for each item id on the current page of the inventory.

Clicking the individual sell id buttons could either create a new command confirming sell if possible, or display using the current command embed.

This is sort of what I imagine it looking like:

### Examples
<img src="https://user-images.githubusercontent.com/22659210/235319266-a668ed4c-56ee-4824-8a28-2f7a47a386d3.png" width=50% height=50%><img src="https://user-images.githubusercontent.com/22659210/235319292-e1083a0a-cf95-4241-97d4-fdcb08a52c20.png" width=50% height=50%>
`Weapon Page w/ Sell Button (left) and, after clicking, w/ Sell Controls (right).`

**Comment by JanikCodes** [comment]
Interesting. I'll have a look.

**Comment by JanikCodes** [comment]
I would close this now due to recent PR #31 that adds a lot of new sell options.
