### ISSUE TITLE
Boss items are available via /explore

### ISSUE THREAD

**Issue by JanikCodes** [JanikCodes/tarnished_souls#12]
Right now important boss items are freely available and obtainable with /explore.
We need to add a new attribute called
"obtainable": false
to the weapons.json and armor.json files.

**Comment by daakru** [comment]
I've been thinking about this, and I feel like it could be beneficial to instead make an attribute that represents what methods are available to obtain each item.

Would something like this "obtainedFrom" attribute be reasonable?
```
      "id":"17f69a18c12l0i1p6irjv6m8ue2f5",
      "name":"Blasphemous Blade",
      "image":"https://eldenring.fanapis.com/images/weapons/17f69a18c12l0i1p6irjv6m8ue2f5.png",
      "description":"Sacred sword of Rykard, Lord of Blasphemy. Remains of the countless heroes he has devoured writhe upon the surface of this blade. Now they share the same blood, bound together as family. Some HP is restored upon defeating an enemy.",
      "obtainedFrom":[
         {
            "source":"boss",
            "id":"rykard_lord_of_blasphemy"
         }
      ],
```

**Comment by JanikCodes** [comment]
I disagree. This limits us when we want to make the item obtainable in other ways.
We have the table `enemy_has_item` where we would put items that specific enemy can drop. 
So it's only neccessary to have that boolean set to false in the .json and simply mark them as unobtainable.

Once that's done I'll add the unobtainable items to each boss with a certain drop chance, so grinding them will be possible :))

**Comment by daakru** [comment]
If we want to make items only found by exploring specific areas would we add a table `location_has_item`?

**Comment by JanikCodes** [comment]
Theoretically yes, but that's not planned atm.
But possible yeah.

**Comment by JanikCodes** [comment]
@daakru FYI we've added a new table to the database in our new branch where locations can drop certain items.
But the original issue with boss items being freely obtainable still persists without the changes to the JSON.

As I said on Discord DM's, Updating our JSON actually updates the items now, which is great.
