### ISSUE TITLE
Suggestion - Change `/fight` to be Solo functionality by default with optional argument `visibility:Public`

### ISSUE THREAD

**Issue by daakru** [JanikCodes/tarnished_souls#20]
Change the `visibility` argument of `/fight` to be optional (like how the `user` argument is on `/character` now). This would make starting up solo fights much less tedious on mobile.

In the future you could add a friend or party system and have visibility options for Public, Friends, Party, etc.

**Comment by JanikCodes** [comment]
This is planned and will be implemented soon.
The lobby system had a small rework planned anyways, to make it more appealing and intuitive.
