### ISSUE TITLE
Visual Indicator for Items with Bonus Stats

### ISSUE THREAD

**Issue by daakru** [JanikCodes/tarnished_souls#9]
When browsing items in my inventory, I would like to be able to easily tell which one has a bonus stat so that I can avoid selling them instead of the base stat version.

This could be done a variety of ways, including but not limited to
* Showing an additional emote or even a \* character next to the name
* Add a command to view the full details of a single item, including a field for the Bonus if any
* Display the damage/armor value as "**\<pre-bonus\>** +\<bonus\>" e.g., "`Damage:` **321** +4" instead of "`Damage:` **325**"

**Comment by JanikCodes** [comment]
Thanks, I agree. 
I thought about it early on but haven't changed it yet. 
Will add that with the upcoming patch.
